---
- hosts: all
  sudo: yes
  tasks:

    - name: Install curl and update cache
      apt: name=curl update_cache=yes

    - name: Run the docker installation script
      shell: curl -sSl https://get.docker.com/ | sh

    - name: Put vagrant into "docker" group
      user: name=vagrant groups=docker append=yes

    - name: Change the docker daemon dns settings
      lineinfile: dest=/etc/default/docker regexp=#DOCKER_OPTS line="DOCKER_OPTS="-H tcp://0.0.0.0:2375"

    - name: Make sure service docker is restarted
      service: name=docker state=restarted
