---
- hosts: all
  sudo: yes
  tasks:

    - name: Install curl and update cache
      apt: name=curl update_cache=yes

    - name: Run the docker installation script
      shell: curl -sSl https://get.docker.com/ | sh

    - name: Put vagrant into "docker" group
      user: name=vagrant groups=docker append=yes

    - name: Refresh facts
      action: setup

    - name: Change the docker daemon dns settings
      lineinfile: dest=/etc/default/docker regexp=#DOCKER_OPTS line="DOCKER_OPTS='--dns {{ facter_ipaddress_docker0 }} --dns 8.8.8.8 --dns-search service.consul'"

    - name: Make sure service docker is restarted
      service: name=docker state=restarted
