VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.ssh.insert_key = false

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
    end

    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "512"]
    end

    config.vm.define "larry" do |server|
        server.vm.hostname = "larry"
        server.vm.box = "ubuntu/trusty64"
        server.vm.network :private_network, ip: "10.0.15.21"
    end

    config.vm.define "curly" do |server|
        server.vm.hostname = "curly"
        server.vm.box = "ubuntu/trusty64"
        server.vm.network :private_network, ip: "10.0.15.22"
    end

    config.vm.define "moe" do |server|
        server.vm.hostname = "moe"
        server.vm.box = "ubuntu/trusty64"
        server.vm.network :private_network, ip: "10.0.15.23"
    end
end
